### PR TITLE
Make Cross-browser fixes and general adjustments

### LINKED ISSUE #3886: Additional home page updates
### Please notify me before merging these changes

---

1) Background of video player should be #007482 in case of awkward screen sizes 
video

2) Please look into the issue with commas not showing up in Safari on the number of classifications 
commas

3) Border of project cards should be #CBCCCB 

4) Remove the "listen to the zooniverse" link in the paragraph under number of classifications

5) Remove the full stop at the end of "Meet the researchers" headline

6) Add a line between the first and second Daily Zoo post, 30px under the white box and 30px above the next item

7) Change "Newest project" to "Latest project" in the social section

8) Change "Recent project updates" to "Project updates"

### PR DESCRIPTION
**Pull request by wgranger**
Fixes #3886 

Describe your changes.
More landing page adjustments based on the issue. This also fixes an issue that is currently visible on mobile view where the project cards don't switch to column view correctly.

# Review Checklist

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [x] Did you deploy a staging branch?
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

https://homepage-updates.pfe-preview.zooniverse.org/

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

File: app/pages/home-not-logged-in/research.jsx [hunk 1]
```diff
@@ -43,7 +39,7 @@ counterpart.registerTranslations('en', {
 const HomePageResearch = (({ count, screenWidth, showDialog, volunteerCount }) =>
   <section className="home-research">
     <Translate className="tertiary-kicker" component="h2" content="researchHomePage.works" />
-    <span className="class-counter">{count.toLocaleString()}</span>
+    <span className="class-counter">{count.toString().replace(/.(?=(?:.{3})+$)/g, '$&,')}</span>
```
Comment (wgranger) [inline app/pages/home-not-logged-in/research.jsx]: I was unable to recreate this issue on Safari (browsers not inserting commas in large numbers with `.toLocaleString()`, but this regex should work just the same.

File: css/home-page.styl [hunk 2]
```diff
@@ -439,6 +440,10 @@ $flex-section
           &:nth-child(odd)
             justify-content: flex-end
 
+        @media (max-width: 400px)
+          flex-basis: 100%
+          flex-direction: column
+
```
Comment (wgranger) [inline css/home-page.styl]: This extended media query was necessary as `flex-basis` is used primarily in the above media queries to keep project cards breaking two at a time instead of stranding a sole card on a line alone. Mobile Safari wasn't breaking into column with the small viewport.

File: app/pages/home-not-logged-in/research.jsx (hunk 1 above)
Comment (srallen) [inline app/pages/home-not-logged-in/research.jsx]: Some languages use periods rather than commas for the thousands separator and `toLocaleString` will properly format that. I think it'd be best to stick with that.

Comment (wgranger) [inline app/pages/home-not-logged-in/research.jsx]: Yeah, originally this issue came up because it was reported `.toLocaleString()` wasn't working on a Safari browser, and I'm suspecting it was an older version of the browser. The `.toLocaleString()` function appears to work on current Safari. 

This brings up a question about browser support. Should we make concessions to support older versions of a browser or expect browsers to be up to date?

File: css/home-page.styl (hunk 2 above)
Comment (srallen) [inline css/home-page.styl]: Maybe CSS multi-column spec would work better than flex in this case? https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Using_multi-column_layouts

File: app/pages/home-not-logged-in/research.jsx (hunk 1 above)
Comment (srallen) [inline app/pages/home-not-logged-in/research.jsx]: Our policy generally is we support current version and the most recent previous version only. MDN reports that Safari 10 should support it. If the issue is being seen in Safari 9, we could look into polyfilling it. Looks like the service we use will do it, if we specify: https://github.com/Financial-Times/polyfill-service/issues/359

File: css/home-page.styl (hunk 2 above)
Comment (rogerhutchings) [inline css/home-page.styl]: Or [Grommet Tiles](https://grommet.github.io/docs/tiles)?

**Comment by mcbouslog** [comment]
code and [the staged branch](https://homepage-updates.pfe-preview.zooniverse.org/) LGTM. 
@beckyrother - thoughts on final review?

**Comment by beckyrother** [comment]
Looks good! Thanks for checking.
