### PR TITLE
Remove classification change listener

### LINKED ISSUE #4296: Hide previous marks not working since #4277
Related to changes in #4277 - the hide previous marks are not working.

## Expected behavior
Hide previous marks should hid current drawing tasks annotations on the subject viewer.
## Current behavior
Hide previous marks does not hide any drawing annotations but can remove them entirely.

## Steps to replicate

Goto https://classification-update.pfe-preview.zooniverse.org/projects/penguintom79/seabirdwatch/classify and draw some marks then try to use hide previous marks checkbox

## Additional information
Related to the change listener PR in #4277.

- **Operating system:**
- **Browser:**

### PR DESCRIPTION
**Pull request by eatyourgreens**
Staging branch URL: https://classification-update.pfe-preview.zooniverse.org

Fixes #4296

Repeat of #4277 but this should properly account for drawing tasks when they are used as part of combo tasks.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

File: app/classifier/task.jsx [hunk 1]
```diff
@@ -11,8 +11,9 @@ class Task extends React.Component {
 
   handleAnnotationChange(newAnnotation) {
     const { classification } = this.props;
-    classification.annotations[classification.annotations.length - 1] = newAnnotation;
-    classification.update('annotations');
+    const annotations = classification.annotations.slice();
+    annotations[annotations.length - 1] = newAnnotation;
```
Comment (camallen) [inline app/classifier/task.jsx]: OOI why does this replace the last existing annotation with the new one, is it because the last one was a default? 

I tried to trace how the new default annotation gets it's actual value stored and it looks like it's in the specific task component on a change event. If that is so then any default will be updated to be a real one, right? Or i am way off track?

File: app/classifier/tasks/drawing/hide-previous-marks-toggle.cjsx [hunk 2]
```diff
@@ -18,7 +18,7 @@ HidePreviousMarksToggle = React.createClass
   setPreviousMarks: (count) ->
     @_lastKnownAnnotationCount = @props.classification.annotations.length
     @props.classification._hideMarksBefore = count
-    @props.onChange @props.classification
+    # @props.onChange @props.classification
```
Comment (camallen) [inline app/classifier/tasks/drawing/hide-previous-marks-toggle.cjsx]: remove / re-instate if this is not / required

File: app/classifier/task.jsx (hunk 1 above)
Comment (eatyourgreens) [reply app/classifier/task.jsx]: This expects to get an updated annotation when a task changes. It simply overwrites your previous annotation, for this task, with the new one.

Comment (eatyourgreens) [reply app/classifier/task.jsx]: The callback then forces a re-render by updating `state.annotations` in the classifier.

**Comment by eatyourgreens** [comment]
I've added a fix for Hide Previous Marks (#4296)

File: app/classifier/task.jsx (hunk 1 above)
Comment (camallen) [reply app/classifier/task.jsx]: right, got it.

File: app/classifier/tasks/drawing/hide-previous-marks-toggle.cjsx [hunk 3]
```diff
@@ -7,18 +7,17 @@ HidePreviousMarksToggle = React.createClass
...
+  getInitialState: ->
+    checked: false
 
   setPreviousMarks: (count) ->
-    @_lastKnownAnnotationCount = @props.classification.annotations.length
     @props.classification._hideMarksBefore = count
-    @props.onChange @props.classification
+    checked = count > 0
+    @setState { checked }
+    # this is a hack to force the parent to render again with marks hidden
```
Comment (camallen) [inline app/classifier/tasks/drawing/hide-previous-marks-toggle.cjsx]: should this be extracted to a function with a name like `force_parent_render_hack()` to signify the intention of it? 

It might allow the removal of the comment and the commit history could store the context of the reason for that code?

Comment (eatyourgreens) [reply app/classifier/tasks/drawing/hide-previous-marks-toggle.cjsx]: That's not a bad idea, though the linter would make us call it `forceParentRender` because it complains if names aren't camel-case.

Comment (camallen) [reply app/classifier/tasks/drawing/hide-previous-marks-toggle.cjsx]: i can't help myself when writing code snippets these days, i should have 🐫'd it

**Comment by eatyourgreens** [comment]
Probably needs a rebase now that #4283 has merged.

**Comment by eatyourgreens** [comment]
Rebased and re-staged.

**Comment by eatyourgreens** [comment]
I've run through every task in the dev classifier now, and haven't been able to find a problem with this.

**Comment by simoneduca** [comment]
Let's do this (after rebasing)!

**Comment by eatyourgreens** [comment]
@simoneduca does this still need rebasing?

**Comment by mcbouslog** [comment]
It appears this causes the feedback modal to show twice:
https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/feedback-testing-mb/classify?reload=0&workflow=3133

^ moved from #4292

**Comment by simoneduca** [comment]
What's the status of this @eatyourgreens? I don't think so, but has the issue with the modal been fixed?

**Comment by eatyourgreens** [comment]
@simoneduca the issue with the modal is a bug in the experimental feedback feature. This PR is waiting on someone to test it and confirm it works (or request changes.)

Actually reading back, sounds like [you've already tested it](#issuecomment-358609243).

**Comment by simoneduca** [comment]
Yeah I couldn't find anything wrong, but I wasn't sure if the modal issue was caused by this. basically I didn't understand why it was referenced here.

**Comment by eatyourgreens** [comment]
This PR changes how annotation changes are reflected in classifier state. Basically, any change in an annotation updates classifier state now, so that we don't miss annotation changes when we pass annotations down to child components.

Feedback relied on the old behaviour, which I _think_ had bugs, to detect when annotations had changed and feedback should be shown.

**Comment by simoneduca** [comment]
Sounds like it's good to go then.
