### PR TITLE
Remove hardcoded # from CFE classify links

### LINKED ISSUE #4358: PFE wrongly assumes that all apps need a `#`
## Expected behavior
Being redirected to the correct page
## Current behavior
User sees the home page (host address), regardless of what the fragment identifier specifies. E.g. https://www.antislaverymanuscripts.org/#/classify just brings up the site homepage.

## Steps to replicate

1. Go to https://www.antislaverymanuscripts.org
2. Click on the project's talk link
3. Click on the classify link

## Additional information
The culprit is this [line of code](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/components/ProjectNavbar/helpers/getProjectLinks.js#L50), which wrongly assumes that all apps need a `#`.

##Suggestion to fix this

1. Remove `#` from the line above.
2. Add `#`, or `#!` for our angular apps, to the project's `redirect` field as needed.

### PR DESCRIPTION
**Pull request by simoneduca**
~**DO NOT MERGE**, until all `project.redirect` value has been updated accordingly.~

Staging branch URL: https://fix-custom-frontend-links.pfe-preview.zooniverse.org/projects/bostonpubliclibrary/anti-slavery-manuscripts/talk?env=production

Fixes #4358 

Describe your changes.
Removes `#` from CFE classify links both the in the current and the new navbar.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by srallen** [comment]
Just a heads up that #4366 is removing the old project navbar, so this PR and that one will need some coordination.

**Comment by shaunanoordin** [comment]
@simoneduca all affected projects have been updated. But do note @srallen's comments regarding #4366, though!

| Project | Old URL | New URL | Notes |
| ------- | ------- | ------- | ----- |
| zooniverse/sunspotter | http://sunspotter.org | http://sunspotter.org/#/ | |
| zooniverse/andromeda-project | http://andromedaproject.org | http://andromedaproject.org/#!/ | Uh, home page is #!/home, not #!/ |
| zooniverse/science-gossip | http://sciencegossip.org | http://sciencegossip.org/#/ | |
| zooniverse/microplants | http://microplants.zooniverse.org | http://microplants.zooniverse.org/#/ | |
| zooniverse/galaxy-zoo | http://galaxyzoo.org | http://galaxyzoo.org/#/ | |
| zooniverse/plankton-portal | http://planktonportal.org | http://planktonportal.org/#/ | |
| zooniverse/worm-watch-lab | http://wormwatchlab.org | http://wormwatchlab.org/#/ | |
| drrogg/annotate | https://anno.tate.org.uk/ | https://anno.tate.org.uk/#!/ | CFE still needs an update |
| zooniverse/planet-hunters | http://planethunters.org | http://planethunters.org/#/ | |
| zooniverse/condor-watch | http://condorwatch.org | http://condorwatch.org/#/ | |
| zooniverse/operation-war-diary | http://operationwardiary.org | http://operationwardiary.org/#/ | |
| zooniverse/disk-detective | http://diskdetective.org | http://diskdetective.org/#/ | |
| zooniverse/penguin-watch | http://penguinwatch.org | http://penguinwatch.org/#/ | |
| zooniverse/radio-galaxy-zoo | http://radio.galaxyzoo.org | http://radio.galaxyzoo.org/#/ | |
| zooniverse/space-warps | http://spacewarps.org | http://spacewarps.org/#/ | |
| zooniverse/bat-detective | http://batdetective.org | http://batdetective.org/#!/ | Uh, home page is #!/home. not #! |
| zooniverse/cyclone-center | http://cyclonecenter.org | http://cyclonecenter.org/#/ | |
| zooniverse/snapshot-serengeti-ouroboros | http://snapshotserengeti.org | http://snapshotserengeti.org/#/ | |
| zooniverse/chimp-and-see | http://chimpandsee.org | http://chimpandsee.org/#/ | |
| zooniverse/higgs-hunters | http://higgshunters.org | http://higgshunters.org/#/ | |
| zooniverse/planet-four | http://planetfour.org | http://planetfour.org/#/ | |
| zooniverse/shakespeares-world | http://www.shakespearesworld.org | http://www.shakespearesworld.org/#!/ | CFE still needs an update |
| zooniverse/seafloor-explorer | http://seafloorexplorer.org | http://seafloorexplorer.org/#!/ | Uh, home page is #!/home. not #! |
| zooniverse/wildcam-gorongosa | http://www.wildcamgorongosa.org/ | http://www.wildcamgorongosa.org/#/ | |

**Comment by simoneduca** [comment]
This should be ready to go. Thanks for carrying out all those boring changes @shaunanoordin !

**Comment by simoneduca** [comment]
Restaged https://fix-custom-frontend-links.pfe-preview.zooniverse.org/projects/bostonpubliclibrary/anti-slavery-manuscripts/talk?env=production

**Comment by shaunanoordin** [comment]
Thanks for the update Simone! And whoah, did part of PR #4366 Voltron itself into this PR? There's quite a bit of additional code. OK, gimme a bit to check this out.

**Comment by simoneduca** [comment]
@shaunanoordin sorry. no that's my fault, let me sort it out and i'll give you a shout. That file shouldn't be there at all.

**Comment by simoneduca** [comment]
Here you go.

File: app/pages/project/project-navbar.jsx [hunk 1]
```diff
@@ -0,0 +1,416 @@
...
+        style={opacity}
+      >
+        <Translate content="project.nav.classify" />
+      </span>
+  );
+}
+
+function ClassifyTab({ project, projectPath, workflow, onClick }) {
+  function redirectClassifyLink(redirect) {
+    return `${redirect}classify`;
```
Comment (shaunanoordin) [inline app/pages/project/project-navbar.jsx]: Does the `redirect` variable here assume that the URL ends with a trailing slash? If yes, we'll want to reimplenent the solution from `getProjectLinks`

This `ClassifyTab()` function is running a bit too deep for me to figure out at a glance what sorta data's being passed, so I'll need to check this on a local test.

Comment (simoneduca) [reply app/pages/project/project-navbar.jsx]: that's the old navbar file, it shouldn't have been there in the first place, sorry.

File: app/pages/project/components/ProjectNavbar/helpers/getProjectLinks.js [hunk 2]
```diff
@@ -46,8 +46,8 @@ function getProjectLinks({ project, projectRoles, workflow, user }) {
 
   // For projects with external front ends
   if (redirect) {
-    const newUrl = redirect.replace(/\/?#?\/+$/, '');
-    links.classify.url = `${newUrl}/#/classify`;
+    const redirectUrl = `${redirect.replace(/\/+$/, '')}/classify`;
```
Comment (shaunanoordin) [inline app/pages/project/components/ProjectNavbar/helpers/getProjectLinks.js]: 👍 Nice, this will catch redirect URLs that either end or don't end with slashes (or multiple slashes).
