### PR TITLE
fix: undefined project.slug in Talk search results

### LINKED ISSUE #7067: Talk: search silently errors with 'string contains an invalid character'
## Expected behavior
Talk should try to display comments, even with invalid characters?

## Current behavior
A blank white page, with the error thrown in the dev console.

## Steps to replicate
https://www.zooniverse.org/talk/search?page=11&query=add

## Additional context

There's some text in a comment which Markdown is attempting to parse as a React component.

```sh
The above error occurred in the <perv<|goto|> component:

perv<|goto|
div
Markdown@https://localhost:3735/main.js:222135:7
div
TalkSearchResult@https://localhost:3735/main.js:125106:20
section
div
div
div
TalkSearch
div
Talk
```

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fix an error where `project.slug` is undefined in Talk search results,
leading to raw markdown strings being passed to the HTML parser in
the `Markdown` component.

Staging branch URL: https://pr-7068.pfe-preview.zooniverse.org/talk/search?page=11&query=add&env=production

- Fixes #7067.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

File: app/talk/search-result.jsx [hunk 1]
```diff
@@ -67,7 +70,7 @@ export default class TalkSearchResult extends React.Component {
         )}
         <CommentContextIcon comment={comment} />
         <CommentLink comment={comment} project={this.props.project}>{comment.discussion_title}</CommentLink>
-        <Markdown content={comment.body} project={this.props.project} />
```
Comment (eatyourgreens) [inline app/talk/search-result.jsx:70]: The way to debug this bug was to add `debug` here, which tells `Markdown` to show error messages in the page:
```jsx
<Markdown debug content={comment.body} project={this.props.project} />
```

**Review by shaunanoordin — APPROVED** [review]
## PR Review

This PR fixes an issue where the Talk page crashes when a comment has an invalid(??) slug.

The fix works by providing a fallback `project` resource with a fallback slug, so the Markdown component doesn't crash.

The root problem however may be something more involved: the `<Markdown>` component's error is something along the lines of "Cannot read properties of undefined (reading 'split')", and the Markdown code itself may need to be updated to be more robust. [(Add an existence check in the default-transformer.js maybe?)](https://github.com/zooniverse/markdownz/blob/0c2db1ad8a692fd9d677b95342691929544b0a0d/src/lib/default-transformer.js#L13)

### Testing

Compare:
- fixed: https://local.zooniverse.org:3735/talk/search?page=11&query=add&env=production
- broken: https://www.zooniverse.org/talk/search?page=11&query=add&env=production

### Status

LGTM. Let's get this fix deployed for Talk.

**Comment by eatyourgreens** [comment]
A side effect of this fix is that Talk search results will now be properly formatted again. They've been displayed as raw markdown strings.
