### PR TITLE
Workflow selection updates and bug fixes

### LINKED ISSUE #5188: Several clicks of 'take me to new workflow' to close modal
## Expected behavior
Clicking 'take me to new workflow' should only be needed once. It should load the workflow that is stored in `settings.workflow_id` in the user's project preferences.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
If I'm classifying on level 1, clear the subject queue, and get prompted to try the level I'm promoted to, then it takes several clicks of 'take me to the new workflow' to get the modal to clear. The classifier appears to be loading slowly behind the modal. The only issue in the console I see is:

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

Which traces to: 
https://github.com/zooniverse/Panoptes-Front-End/blob/860e7624fb19c711dcd47d0bbbea490b8ce3164a/app/components/subject-viewer.cjsx#L229

And it's not being properly cleared on timeout. 

I'm also seeing the modal open several times, so it's not the same modal that I'm clicking to proceed on multiple times:

screen shot 2019-01-07 at 11 24 08 am

I didn't see this in previous testing of the recent changes to workflow selection, so I'm not sure why this has started up. 

## Steps to replicate
Using Gravity Spy to test: https://master.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy?env=production with a user that is promoted.

Or my test project: 
https://master.pfe-preview.zooniverse.org/projects/srallen086/workflow-assignment-testing
Start with the beginner workflow and promote your user to workflow id `2334` (journey) and when the subject queue is next clear while classifying on the beginner workflow, you'll be prompted to try the new workflow. 

## Additional information

- **Operating system:**
- **Browser:**

### PR DESCRIPTION
**Pull request by eatyourgreens**
Remove the API client from workflow selection. Instead, use the loadWorkflows redux action once a workflow ID has been selected.

Remove user preference code from workflow selection, since the loadWorkflows action also updates preferences with the selected workflow, if successful.

Update the home workflow buttons to check the stored workflow and only load the classifier if the stored workflow matches the workflow for that button.

Check workflow assignment prompt state on the classify page before checking whether to show a new prompt.

Validate the stored workflow against the project before rendering the classifier.

Staging branch URL: https://pr-5198.pfe-preview.zooniverse.org

Fixes #5188.

# Required Manual Testing

- [x] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [x] Does the projects page render correctly?
- [x] Can you load project home pages?
- [x] Can you load the classification page?
- [x] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [x] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This PR updates the project workflow buttons to behave more like links, which made me feel more strongly that those buttons should just be links, and we should allow all projects to link to workflows by ID in the classify page URL, as per #5125.

**Comment by shaunanoordin** [comment]
Quick notes:
- Basic testing (login/logout, Projects page, Project pages, ability to submit Classifications on a test project) look good on OSX+Chrome
- code changes LGTM with no glaring issues, though I'll need a second read through to make sure I'm following the logic flow correctly.
- Manual testing is taking a bit longer since I have no idea how to perform promotions on myself.

**Comment by eatyourgreens** [comment]
NB. the fix for #5188 is the changes in 70de137: check whether we're already showing the prompt before showing it again. The other changes here are tidying up workflow selection, so we don't have the same API code in two places, and making sure the home page buttons don't load a workflow if we're using it already.

File: app/pages/project/workflow-selection.jsx [hunk 1]
```diff
@@ -133,16 +104,9 @@ class WorkflowSelection extends React.Component {
             this.getSelectedWorkflow(this.props);
```
Comment (eatyourgreens) [inline app/pages/project/workflow-selection.jsx]: Should this be replaced with `actions.classifier.loadWorkflow(default_workflow, locale, preferences)`? Loading the default workflow on error seems more sensible to me (as long as we indicate to the user that the workflow has been changed from the one that they thought was loading.)

File: app/pages/project/home/home-workflow-button.spec.js [hunk 2]
```diff
@@ -98,8 +99,36 @@ describe('ProjectHomeWorkflowButton', function () {
...
+    });
+
+    describe('for the current workflow', function () {
+      before(function () {
+        sinon.stub(browserHistory, 'push');
+        wrapper.setProps({ classifierWorkflow: testWorkflowWithoutLevel });
+      });
+
+      after(function () {
+        browserHistory.push.restore;
```
Comment (eatyourgreens) [inline app/pages/project/home/home-workflow-button.spec.js]: Typo. Should be `restore()`.

File: app/pages/project/workflow-selection.jsx (hunk 1 above)
Comment (srallen) [reply app/pages/project/workflow-selection.jsx]: That's a change in behavior that I think we should discuss and if we go forward with it, implement in a separate PR. Even though a lot of projects have default workflows set, not all do, so for what it's worth, I think just running through the strategies again as it does now is overall safer. 

Informing the user is something that @shaunanoordin has brought up and I think better fits as part of the rewrite.

**Comment by eatyourgreens** [comment]
That's annoying. I don't get the type errors when running the tests (using `docker-compose run dev npm run test`.)

Loading state's been removed because the store is updating now, when a workflow loads, so the component reacts to changes in the workflow prop instead.

I'll take a look at why the wrong workflow is being loaded on login. It sounds like workflow selection is mounting while the user prop is still null.

**Comment by eatyourgreens** [comment]
I can reproduce that sign-out/sign-in problem on the classify page, with my user account, on this branch, but not on https://master.pfe-preview.zooniverse.org/projects/srallen086/workflow-assignment-testing/classify so it's definitely a problem with this PR.

File: app/pages/project/workflow-selection.jsx [hunk 3]
```diff
@@ -31,7 +29,9 @@ class WorkflowSelection extends React.Component {
     const currentUser = user && user.login;
     const userSelectedWorkflow = (preferences && preferences.preferences) ? this.sanitiseID(preferences.preferences.selected_workflow) : undefined;
     if (userSelectedWorkflow && workflow) {
-      if (!this.state.loadingSelectedWorkflow && userSelectedWorkflow !== workflow.id) {
+      const prevWorkflowID = prevProps.workflow && prevProps.workflow.id;
+      const workflowChanged = workflow.id !== prevWorkflowID;
+      if (workflowChanged && userSelectedWorkflow !== workflow.id) {
```
Comment (eatyourgreens) [inline app/pages/project/workflow-selection.jsx]: This change isn't loading a new workflow, from preferences, when a user logins in. Possibly because `userSelectedWorkflow` doesn't change at the same time as the stored workflow. This should maybe listen for a change in user ID, or a change in user preferences ID, rather than a change in workflow ID.

**Comment by eatyourgreens** [comment]
>I found a regression testing https://pr-5198.pfe-preview.zooniverse.org/projects/srallen086/workflow-assignment-testing/classify. If visiting the classify page signed out, the default workflow, id 2333, loads. I sign in, then the classifier resets and loads the default workflow again instead of my UPP selected workflow which is id 2334. What should happen is the workflow selection shouldn't run until the the UPP request finishes and the state is set on the ProjectPageController.

Changing the component to reset the classifier on preferences change, rather than user change, fixes this.

File: app/pages/project/workflow-selection.jsx [hunk 4]
```diff
@@ -60,17 +52,11 @@ class WorkflowSelection extends React.Component {
     ) {
       selectedWorkflowID = workflowFromURL;
       activeFilter = false;
```
Comment (eatyourgreens) [inline app/pages/project/workflow-selection.jsx]: The active filter isn't being used by Gravity Spy, only by Notes from Nature. Is that correct?

File: app/pages/project/workflow-selection.jsx (hunk 1 above)
Comment (eatyourgreens) [reply app/pages/project/workflow-selection.jsx]: Looking at the code, this line only runs if `project.configuration` exists but the selected workflow ID is not the project default. There's no check to see if a project default actually does exist so changing this would introduce bugs.

If there is a workflow loaded at this point, then `actions.classifier.reset()` later in this block will also force selection to run again, since changing the stored workflow unmounts and remounts workflow selection (and the classifier.)

Comment (eatyourgreens) [reply app/pages/project/workflow-selection.jsx]: These nested if blocks are also very confusing.

File: app/pages/project/workflow-selection.jsx (hunk 3 above)
Comment (eatyourgreens) [reply app/pages/project/workflow-selection.jsx]: Resolved by deleting this block of code and checking for a change of preferences instead.

**Comment by eatyourgreens** [comment]
@srallen I don't see any type errors in [the tests on Travis](https://travis-ci.org/zooniverse/Panoptes-Front-End/builds/479795673), so I think this is ready now.

File: app/pages/project/workflow-selection.jsx (hunk 4 above)
Comment (srallen) [reply app/pages/project/workflow-selection.jsx]: The active filter is true for most projects' workflows, but changed to false if the user is an admin, project owner, tester, or expert that may have a reason to load an inactive workflow. `this.checkUserRoles(project, user)` this returns true for these user roles and then the active filter is changed to false.

For Notes from Nature, the next set of conditions is for them and projects like them. 
```
else if (workflowFromURL &&
      project.experimental_tools &&
      project.experimental_tools.indexOf('allow workflow query') > -1
    ) {
      selectedWorkflowID = workflowFromURL;
```

The active filter isn't changed and stays true.

Comment (eatyourgreens) [reply app/pages/project/workflow-selection.jsx]: I forgot about previewing workflows in development. 😳 

I remember we talked about workflow assignment for inactive workflows on #5171 where you mentioned owners being able to load inactive workflows, so thought I'd check because the workflow selection code does not allow that.
https://github.com/zooniverse/Panoptes-Front-End/pull/5171#pullrequestreview-189074992

Comment (eatyourgreens) [reply app/pages/project/workflow-selection.jsx]: Easy enough to change though, by setting the filter from the user roles earlier in the code.
`let activeFilter = this.checkUserRoles(project, user);`

**Comment by eatyourgreens** [comment]
I can reproduce that too. The crash is happening in the `HidePreviousMarksToggle`, which I think you've come across before? I can't reproduce the crash on staging, switching between I Fancy Cats and my own test project. My test project has a default workflow, but I think American Soldier might not have one.

On staging and production, I'm also seeing the tutorial for the previous project open eg. on production, American Soldier launches the tutorial for TESS.

I'm packing up for the day but I'll look into this tomorrow.

**Comment by eatyourgreens** [comment]
I think that crash is the same bug as #5162.

**Comment by srallen** [comment]
I was using The American Soldier to test random workflow selection. I can't get this issue to replicate on master using the same steps I was using before, so I'm not sure if it is the same as #5162

**Comment by eatyourgreens** [comment]
I’m seeing the same error message and stack trace as #5162. `HidePreviousMarksToggle` is attempting to update a null classification.

**Comment by eatyourgreens** [comment]
@srallen I've updated the redux action and `HidePreviousMarksToggle` to guard against updating null classifications or undefined annotations. I'm not going to mark #5162 as fixed, though, because that component should not be updating the classification, as noted in the comments on #5162.

**Comment by eatyourgreens** [comment]
I've also updated the workflow selection render method to validate workflows against the project before rendering the classifier. That should prevent American Soldier from rendering the TESS workflow while the American Soldier workflow is loading.

File: app/pages/project/workflow-selection.jsx [hunk 5]
```diff
@@ -197,8 +148,10 @@ class WorkflowSelection extends React.Component {
   }
 
   render() {
-    const { loadingSelectedWorkflow } = this.state;
-    return loadingSelectedWorkflow ? <p>Loading workflow</p> : this.props.children;
+    const { children, project, workflow } = this.props;
+    const linkedWorkflows = project.links.workflows || [];
+    const workflowExistsForProject = workflow && linkedWorkflows.indexOf(workflow.id) > -1;
```
Comment (eatyourgreens) [inline app/pages/project/workflow-selection.jsx]: Should this be inverted and check `workflow.links.project` against the project ID?
