### PR TITLE
Fix project search external links

### LINKED ISSUE #3228: Search Bar Bug
## Expected behavior
Should be able to search and go to project

## Current behavior
It goes back to home screen. I have a video of the behavior if you want to check it out

## Steps to replicate
Go to Project Page type something into the search bar and click on the result

- **Operating system:**
iOS 10.10.5

- **Browser:**
Chrome

### PR DESCRIPTION
**Pull request by camallen**
Fixes #3228 - Allow external links to navigate correctly and avoid double lookups via the api.

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [X] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [X] Did you deploy a staging branch? https://project_search_external_links.pfe-preview.zooniverse.org/
- [ ] Did you get any type checking errors from [Babel Typecheck](https://github.com/codemix/babel-plugin-typecheck)

## Optional

- [ ] If it's a new component, is it in ES6? Is it clear of warnings from ESLint?
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?

### CODE REVIEW

File: app/pages/projects/projects-search-selector.jsx [hunk 1]
```diff
@@ -11,14 +11,12 @@ class SearchSelector extends Component {
...
-    apiClient.type('projects').get(projectId)
-      .then(project => {
-        if (project.redirect != null && project.redirect.length !== 0) {
-          return browserHistory.push(project.redirect);
-        }
-        return browserHistory.push(['/projects', project.slug].join('/'));
-      });
+  navigateToProject(projectUrl) {
+    if (projectUrl.match(/^http.*/)) {
+      window.location.href = projectUrl;
```
Comment (eatyourgreens) [inline app/pages/projects/projects-search-selector.jsx]: I think this should be `window.location = projectUrl;` or `window.location.assign(projectUrl);` as per the first example at https://developer.mozilla.org/en-US/docs/Web/API/Window/location

Comment (simoneduca) [inline app/pages/projects/projects-search-selector.jsx]: How come we don't need the api call anymore? Where is projectId passed to navigateToProject?

Comment (camallen) [inline app/pages/projects/projects-search-selector.jsx]: Because all you needed was the project slug / redirect that i pass in from the previous api calls as the value on the select (they are all uniq URL's / slugs).

**Comment by camallen** [comment]
@eatyourgreens updated - thanks for the doc links.

**Comment by eatyourgreens** [comment]
:+1:
