### PR TITLE
Rubin 2025 Landing Page pt4: improve html+accessibility, various fixes 

### LINKED ISSUE #7319: Rubin & Accounts pages: Register Form causes logout when checking for existing users
## Authentication Issue

Associated: #7310 

The Register Form (used by both the Rubin landing page and the Accounts page) has an issue where, if you're already logged in, then you might **accidentally be logged out** with _no warning and no indication of having done so,_ if you either (1) have a login-autofill on your browser, or (2) you type in something in the register form.

Reproduction 1:
- Login to Zooniverse.org
- Go to either https://www.zooniverse.org/accounts/register
- Either...
  - Type in something into the username field
  - If you have a login auto-fill feature, your username might already be filled.
  - (Basically, you want to trigger the "username" field's onChange action, which checks for conflicting usernames.)
- Observe that you're now logged out.

Reproduction 2:
- Login to Zooniverse.org
- Go to https://www.zooniverse.org/rubin
- If you have a login auto-fill feature, your username might already be filled (thus triggering the onChange action)
  - If you don't have a login auto-fill... _click on the username text field very very quickly and type in something before the form realises you're logged in and switches out the Register Form for the Call to Action._
- Observe that you're now logged out.

Analysis:
- The "username" input field's onChange will trigger `checkForLoginConflict()`, which in turn will log out
- Immediate solution (for Rubin) is to either:
  - Make sure the Rubin page waaaits for user checks to complete (app.initialised or something like that) before rendering anything, or
  - _Not_ log out users if they find a conflict. Not sure why that was there to begin with.
- Immediate solution (for /accounts page) is to:
  - quickly back-port all solutions from the Rubin landing page back to /accounts.
- Better solution would be to rewrite the code to remove promise handlers, but by definition that's what FEM is for.

See:
- Initial report on Rubin landing page (/rubin) [(link)](https://github.com/zooniverse/Panoptes-Front-End/issues/7310#issuecomment-2970955372)
- Second reproduction, also confirms this happens on /accounts [(link)](https://github.com/zooniverse/Panoptes-Front-End/issues/7310#issuecomment-2970987230)
- Confirmation that issue only occurs with either (1) login auto-fill or (2) typing into the username field in /accounts [(link)](https://github.com/zooniverse/Panoptes-Front-End/issues/7310#issuecomment-2971224217)
- Analysis pointing that the issue stems from checkForLoginConflict() [(link)](https://github.com/zooniverse/Panoptes-Front-End/issues/7310#issuecomment-2971640937)
- ⚠ A note added that promiseToSetState() and handleInputChange() has (or _should_ have) been deprecated. [(link)](https://github.com/zooniverse/Panoptes-Front-End/issues/7310#issuecomment-2971644880)

Credit to @eatyourgreens for spotting the issue.

### Dev Notes

This bug is extant on the standard PFE register form as well (i.e. the one you see when you click "Register" on the top header) but hasn't been noticed since the Register form is more successfully hidden when a user is logged in. (i.e. you can't click "Register")

Image

- It's more noticeable on the Rubin landing page since there's a delay between page load and user login check (i.e. Rubin is rendering even before the app fully initialises), giving space for a login auto-fill to trigger the username field input change.
- It's _very_ noticeable on /accounts, but then again, nobody seems to have noticed /accounts was incredibly broken to begin with.

### Status

I'm marking this as a medium priority issue. In the planned work hierarchy:

- the Rubin page should be fixed before /rubin goes public, but shouldn't be considered a hard blocker.
- the /accounts page is already borked as heck yet nobody has noticed, so this just goes on the pile of fixes that will be back-ported in Rubin Part 6.

### PR DESCRIPTION
**Pull request by shaunanoordin**
## PR Overview

Part of: Rubin 2025 Landing Page (#7310)
Follows: #7318
Also: fixes #7319 

This PR is part of a project that adds a special landing page for the Rubin 2025 project. The scope of Part 4 is to improve accessibility even further (notably for the RegisterForm, taking notes from feedback in 7318), clean up the HTML of the register forms, (and probably clean up the CSS too,) and apply various fixes.

Now that the [Rubin page is live](https://www.zooniverse.org/rubin), a _meta-goal_ for Part 4 is the **prepare the code for back-porting the Sign In and Register functionality to the /accounts page**.

RegisterForm:
- Improve accessibility:
  - [x] error messages should appear next to the input element. Use aria-describedby/labelledby [(comment)](https://github.com/zooniverse/Panoptes-Front-End/pull/7318#discussion_r2133788429)
  - [x] prevent auto-focus [(comment)](https://github.com/zooniverse/Panoptes-Front-End/pull/7318#issuecomment-2961390749)
  - [x] add aria-live or aria-describedby for the general "on submit" error messages? [(comment)](https://github.com/zooniverse/Panoptes-Front-End/pull/7318#pullrequestreview-2921408534)
- [x] improve HTML + CSS? (i.e. pls use fewer arbitrary `<br/>`)

SignInForm:
- Improve accessibility:
  - [x] prevent auto-focus [(comment)](https://github.com/zooniverse/Panoptes-Front-End/pull/7318#issuecomment-2961390749)
  - [x] add aria-live or aria-describedby for the general "on submit" error messages? [(comment)](https://github.com/zooniverse/Panoptes-Front-End/pull/7318#pullrequestreview-2921408534)
- [x] improve HTML + CSS?

Rubin Page:
- Improve accessibility:
  - [x] consider aria-selected for tabs [(comment)](https://github.com/zooniverse/Panoptes-Front-End/pull/7318#pullrequestreview-2921408534)

Optional for this PR (can postpone for later part):
- ❌ ~~fix tests~~

Other changes:
- [x] Rubin Page will only render AFTER the app has completed initialisation, i.e. it knows whether a user has logged in or otherwise. (Fixes #7319, supersedes #7320)
- [x] New Rubin paths: `/rubin` (default, starts with Register form), `/rubin/sign-in` (starts with Sign In form), `/rubin/register` (starts with Register form)

Staging branch URL: https://pr-7324.pfe-preview.zooniverse.org/rubin?env=staging

### Testing

**Test case 1:** Core functions

(Same as 7314 just make sure the Sign In and Register functionality works.)

<details>
<summary>Test case 1a: Register function</summary>

- Pretend you're a new user to the Zooniverse.
- Open the Rubin page in an incognito/privacy window. (i.e. make sure you're not logged in. And be sure to use staging, because we're gonna spam our DB)
- Attempt to create a new account.
  - When you successfully create an account, your welcome to the Zooniverse should make sense to you, a new user.
  - e.g. at minimum, you shouldn't be stranded on the register form with no idea what to do next.
- Bonus: also attempt to create an _invalid_ account, e.g. select an existing username, or invalid email. Ensure error messages make sense.
  - 🆕 Try to submit with an obviously wonky email address, e.g. `example@gmail,com`. The code doesn't guard against _every_ invalid email address pattern, but should take care of some of the more obvious ones. (e.g. commas instead of periods)

</details>

<details>
<summary>Test case 1b: Sign In function</summary>

- Open the Rubin page in an incognito/privacy window. (i.e. make sure you're not logged in.)
- Attempt to login.
  - When you successfully login, you should be able to easily understand this fact, and know what to do next.
- Bonus: also attempt to _unsuccessfully_ login. Ensure error messages make sense.

</details>

<details>
<summary>Test case 1c: Already Signed In state</summary>

- Make sure you're already signed in, and then open the Rubin page.
- You should see content appropriate to someone who's signed in.
- You should NOT be able to sign in again, nor register a new account.

</details>

**Test case 2:** Fix for 7319

- Make sure you're already signed in, and then open the Rubin page.
- Ensure that you DON'T see a brief flash of the Register form _before the app finishes initialising_

**Test case 3:** New Rubin paths & starting forms

- While not signed in, open `/rubin`. Ensure the page starts with the Register form.
- Open `/rubin/sign-in`. Ensure the page starts with the Sign In form.
- Open `/rubin/register`. Ensure the page starts with the Register form.
- Note that the paths don't change when you click on the Sign In or Register tabs.

EXTRA CRITERIA:
- All fixes to /rubin should also make sense to [/accounts](https://www.zooniverse.org/accounts), since the code will be back-ported.

### Status

~~WIP~~

2025.06.17: ready for review!

### CODE REVIEW

File: app/rubin-2025/register-form.jsx [hunk 1]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
+          </span>
+        </div>
+
+        <div className="form-row">
+          <div className="label-block">
+            <label htmlFor="register-form-login">
+              <Translate content="registerForm.userName" />
+            </label>
+
+            <div aria-live="polite" id="register-form-login-help-message-1">
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:104]:
```suggestion
            <div id="register-form-login-help-message-1">
```

File: app/rubin-2025/register-form.jsx [hunk 2]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
-            {nameConflict && (
-              <span className="form-help error">
-                <Translate content="registerForm.nameConflict" />{' '}
-                <a href={`${window.location.origin}/reset-password`}>
-                  <Translate content="registerForm.forgotPassword" />
-                </a>
-              </span>
-            )}
+
+            <div aria-live="polite" id="register-form-login-help-message-2">
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:114]:
```suggestion
            <div id="register-form-login-help-message-2">
```

File: app/rubin-2025/register-form.jsx [hunk 3]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
+              {nameConflict && (
+                <span className="form-help error">
+                  <Translate content="registerForm.nameConflict" />{' '}
+                  <a href={`${window.location.origin}/reset-password`}>
+                    <Translate content="registerForm.forgotPassword" />
+                  </a>
+                </span>
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:121]: This can probably be added to the accessible description ofthe input too.

File: app/rubin-2025/register-form.jsx [hunk 4]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
+              )}
+            </div>
+
             {(this.state.input_login?.length > 0
               && nameConflict === false
+              && !("nameConflict" in this.state.pending)
             ) && (
               <span className="form-help success">
                 <Translate content="registerForm.looksGood" />
               </span>
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:131]: This feedback might be good in the field's accessible description too.

File: app/rubin-2025/register-form.jsx [hunk 5]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
             )}
+
             <Translate className="form-help info right-align" content="registerForm.required" />
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:134]: Add this to the form's accessible label so that screenreaders announce the field as required.

File: app/rubin-2025/register-form.jsx [hunk 6]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
+            aria-describedby="register-form-error-message register-form-login-help-message-1 register-form-login-help-message-2"
             className="standard-input full"
             disabled={inputDisabled}
-            autoFocus
-            onChange={this.handleUserInput}
+            id="register-form-login"
             maxLength="255"
+            name="login"
+            onChange={this.handleUserInput}
+            type="text"
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:145]:
```suggestion
            type="text"
            autocomplete="username"
```

[Add autocomplete to input fields](https://www.w3.org/WAI/WCAG21/Techniques/html/H98) to meet WCAG SC 1.3.5.

File: app/rubin-2025/register-form.jsx [hunk 7]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
-          <span className="columns-container inline spread">
-            <Translate content="registerForm.password" />
-            {passwordTooShort && (
-              <Translate className="form-help error" content="registerForm.passwordTooShort" />
+          <div>
+            <Translate component="span" className="form-help info" content="registerForm.whyUserName" />
+            {this.state.underAge && (
+              <Translate component="span" className="form-help info" content="registerForm.notRealName" />
             )}
+          </div>
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:154]: Screenreaders in forms mode will ignore this `<div>` (it's not a form element) so this might need to be added to the field's accessible description too.

File: app/rubin-2025/register-form.jsx [hunk 8]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
-            name="password"
-            id="register-form-password"
-            value={this.state.input_password}
+            aria-describedby="register-form-error-message register-form-password-help-message"
             className="standard-input full"
             disabled={inputDisabled}
+            id="register-form-password"
+            name="password"
             onChange={this.handleUserInput}
+            type="password"
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:178]:
```suggestion
            type="password"
            autocomplete="new-password"
```

File: app/rubin-2025/register-form.jsx [hunk 9]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
+        <div className="form-row">
+          <div className="label-block">
+            <label htmlFor="register-form-email">
+              {this.state.underAge
+                ? <Translate content="registerForm.guardianEmail" />
+                : <Translate content="registerForm.email" />
+              }
+            </label>
+
+            <div aria-live="polite" id="register-form-email-help-message-1">
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:226]:
```suggestion
            <div id="register-form-email-help-message-1">
```

File: app/rubin-2025/register-form.jsx [hunk 10]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
+              {emailInvalidChars && (
+                <Translate className="form-help error" content="registerForm.emailInvalidChars" />
+              )}
+            </div>
+
+            <div aria-live="polite" id="register-form-email-help-message-2">
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:232]:
```suggestion
            <div id="register-form-email-help-message-2">
```

File: app/rubin-2025/register-form.jsx [hunk 11]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
-            {emailConflict && (
-              <span className="form-help error">
-                <Translate content="registerForm.emailConflict" />{' '}
-                <a href={`${window.location.origin}/reset-password`}>
-                  <Translate content="registerForm.forgotPassword" />
-                </a>
-              </span>
-            )}
+
+            <div aria-live="polite" id="register-form-email-help-message-3">
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:242]:
```suggestion
            <div id="register-form-email-help-message-3">
```

File: app/rubin-2025/register-form.jsx (hunk 5 above)
Comment (eatyourgreens) [reply app/rubin-2025/register-form.jsx:134]: Ditto for all the other required fields on the page.

File: app/rubin-2025/register-form.jsx (hunk 4 above)
Comment (eatyourgreens) [reply app/rubin-2025/register-form.jsx:131]: Ditto for all the other "looks good!" feedback messages in the form. It depends whether yoou want a screen reader to hear the "Looks good!" feedback, or if it's intended only for sighted users.

File: app/rubin-2025/register-form.jsx [hunk 12]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
-            name="email"
-            id="register-form-email"
-            value={this.state.input_email}
+            aria-describedby="register-form-error-message register-form-email-help-message-1 register-form-email-help-message-2 register-form-email-help-message-3"
             className="standard-input full"
             disabled={inputDisabled}
+            id="register-form-email"
+            name="email"
             onChange={this.handleUserInput}
+            type="text"
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:272]:
```suggestion
            type="email"
            autocomplete="email"
```

NB. `type="email"` gives you email address pattern-matching for free.

File: app/rubin-2025/register-form.jsx [hunk 13]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
 
-        <label>
-          <span className="columns-container inline spread">
-            <Translate content="registerForm.realName" />
+        <div className="form-row">
+          <div className="label-block">
+            <label htmlFor="register-form-creditedName">
+              <Translate content="registerForm.realName" />
+            </label>
             <Translate className="form-help info right-align" content="registerForm.optional" />
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:282]: Screenreaders will ignore this, so it should be part of either the accessible label or accessible description for the name input.

File: app/rubin-2025/register-form.jsx [hunk 14]
```diff
@@ -79,233 +79,294 @@ class RegisterForm extends React.Component {
...
-            id="register-form-creditedName"
-            value={this.state.input_creditedName}
             className="standard-input full"
             disabled={inputDisabled}
-            title={counterpart('registerForm.realNamePatternHelp')}
+            id="register-form-creditedName"
+            name="creditedName"
             onChange={this.handleUserInput}
+            pattern='[^@]+'
+            title={counterpart('registerForm.realNamePatternHelp')}
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:291]: >If you want to hide content from mobile and tablet users as well as assistive tech users and keyboard only users, use the title attribute.

https://www.tpgi.com/using-the-html-title-attribute-updated/

This title text is hidden from phones, tablets, and screen readers.

File: app/rubin-2025/sign-in-form.jsx [hunk 15]
```diff
@@ -79,15 +86,17 @@ class SignInForm extends React.Component {
...
+                  <Translate content="signInForm.incorrectDetails" />
+                ) : (
+                  <span>{this.state.error.toString()}</span>
+                )}{' '}
+              </div>
+            )}
+          </div>
 
           {this.state.busy ? (
             <LoadingIndicator />
```
Comment (eatyourgreens) [inline app/rubin-2025/sign-in-form.jsx:102]: Using a live region to announce the loading state, as it changes, might make sense. Equally, it might also add extra noise to the page for a blind user.

File: app/rubin-2025/register-form.jsx (hunk 14 above)
Comment (eatyourgreens) [reply app/rubin-2025/register-form.jsx:291]: Obi Wan Kenobi: Title? That's an attribute I haven't seen in a long time.

File: app/rubin-2025/register-form.jsx [hunk 16]
```diff
@@ -79,233 +79,330 @@ class RegisterForm extends React.Component {
...
-            id="register-form-email"
-            value={this.state.input_email}
+            autoComplete="email"
+            aria-describedby="register-form-error-message register-form-email-help-message-1 register-form-email-help-message-2 register-form-email-help-message-3 register-form-email-help-message-looksGood register-form-email-help-message-required"
             className="standard-input full"
             disabled={inputDisabled}
+            id="register-form-email"
+            name="email"
             onChange={this.handleUserInput}
+            type="text"
```
Comment (eatyourgreens) [inline app/rubin-2025/register-form.jsx:299]:
```suggestion
            type="email"
```

The type probably needs to match the input purpose here. See [Technique H100: Providing properly marked up email and password inputs](https://www.w3.org/WAI/WCAG21/Techniques/html/H100).

This won't make a difference in desktop browsers but should provide the email keyboard in mobile browsers and should announce the field as an email input in JAWS or NVDA.

File: app/rubin-2025/register-form.jsx [hunk 17]
```diff
@@ -79,233 +79,330 @@ class RegisterForm extends React.Component {
...
+            autoComplete="name"
+            aria-describedby="register-form-creditedName-help-message-optional register-form-creditedName-help-message-whyRealName"
             className="standard-input full"
             disabled={inputDisabled}
-            title={counterpart('registerForm.realNamePatternHelp')}
+            id="register-form-creditedName"
+            name="creditedName"
             onChange={this.handleUserInput}
+            pattern='[^@]+'
+            title={counterpart('registerForm.realNamePatternHelp')}
```
[the remark this answers is not in the document]
Comment (eatyourgreens) [reply app/rubin-2025/register-form.jsx:324]: Steve Faulkner has this example of the `title` attribute for a form input:

>Examples of `title` attribute use that are NOT USEFUL or are of LIMITED USE:
>…
>Providing additional instructions for a control:
```html
<label for="n1">name</label> <input type="text" title="Please use uppercase." id="n1">
```
>If the instructions are important for using the control correctly, then provide them in text near the control, so they can be read by everyone.

https://www.tpgi.com/using-the-html-title-attribute-updated/

If you are going to use the `title` attribute here, I think you might need to open an issue to note that it fails WCAG 2 level AA.

[the remark this answers is not in the document]
Comment (eatyourgreens) [reply app/rubin-2025/register-form.jsx:324]: After testing with an iPhone and a couple of desktop browsers, there are a couple of WCAG failures in the real name field here:
- @ characters aren't allowed in the real name, but that isn't explained anywhere ([3.3.2: labels or instructions (level A)](https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html).) This would pass if you changed the input label to 'Real name (not an email address)'.
- if I do type an @ character into the real name field, `input.validity.patternMismatch` changes to true but that isn't checked anywhere in the form validation. There's no feedback that I've entered an invalid name, nor how to correct it ([3.3.3 Error suggestion (level AA)](https://www.w3.org/WAI/WCAG22/Understanding/error-suggestion.html).) See [Progressively Enhanced Form Validation](https://cloudfour.com/thinks/progressively-enhanced-form-validation-part-1-html-and-css/) how to use [the `ValidityState` API](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState) to build accessible form validation (via [Avoid Default Field Validation](https://adrianroselli.com/2019/02/avoid-default-field-validation.html) which is also worth reading to learn how default validation in browsers fails accessibility tests.)

I'm assuming the accessibility requirement for Rubin is still WCAG 2 level AA but that may well have changed.

[the remark this answers is not in the document]
Comment (eatyourgreens) [reply app/rubin-2025/register-form.jsx:324]: Here's a screenshot in desktop Chrome. The relaname field contains invalid characters, but it looks like I can still press Register and submit the form.

The registration form in Chrome. All the fields have been filled out with valid values, except for 'Real name', which says '@eatyourgreens'. There are no error messages and the submit button is enabled, ready to submit.

**Comment by shaunanoordin** [comment]
## PR Update

- RegisterForm:
  - email input now uses type=input
  - real name input now removes pattern and title

❗ Please note that the scope of this PR has grown beyond the intent of part 4, and has significantly exceeded the planned development time. Additional feedback on _blocking issues,_ if any, will still be welcome.

**Review by mcbouslog — APPROVED** [review]
Tested locally as noted without issue, LGTM! 🚀 

Confirmed sign in, error messages, and my password manager interaction is all as expected. Confirmed registration inputs work as expected, including warnings and success.
