### PR TITLE
Fix type error on collections page

### LINKED ISSUE #4682: CollectionPage crashes if not signed in
## Expected behavior
I should be able to browse collections if not signed in.

## Current behavior
Opening a collection kills the React app with an uncaught type error.
```
Uncaught TypeError: Cannot read property 'id' of null
    at CollectionPage._this.canCollaborate (eval at <anonymous> (main.js:5543), 
    at CollectionPage.componentDidMount (eval at <anonymous> (main.js:5543),
```

## Steps to replicate
Open any project collection while not signed in.

## Additional information
Reported by `maricksu` on Talk: 
https://www.zooniverse.org/talk/17/658795?comment=1097207

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fix an error where the collections page crashed if `props.user` is null. Only checks `user.id` if user is defined.

Staging branch URL: https://collections.pfe-preview.zooniverse.org

Fixes #4682.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

File: app/collections/show.jsx [hunk 1]
```diff
@@ -52,19 +52,20 @@ class CollectionPage extends React.Component {
...
         const isCollaborator = role.roles.includes('collaborator');
-
         return isCollaborator && idMatch;
       });
+      isOwner = this.props.user.id === this.props.owner.id;
     }
-    const isOwner = this.props.user.id === this.props.owner.id;
 
     this.setState({ canCollaborate: canCollaborate || isOwner });
   };
```
Comment (rogerhutchings) [inline app/collections/show.jsx]: Should there be a semi-colon here?

File: app/collections/show.jsx [hunk 2]
```diff
@@ -52,19 +52,20 @@ class CollectionPage extends React.Component {
...
+      isOwner = false;
     } else {
       canCollaborate = this.props.roles.some((role) => {
         const idMatch = (role.links.owner.id === this.props.user.id);
         const isCollaborator = role.roles.includes('collaborator');
-
         return isCollaborator && idMatch;
       });
+      isOwner = this.props.user.id === this.props.owner.id;
     }
```
Comment (rogerhutchings) [inline app/collections/show.jsx]: This could be simplified a bit:

```
    let canCollaborate = false;
    let isOwner = false;
    if (this.props.user) {
      canCollaborate = this.props.roles.some((role) => {
        const idMatch = (role.links.owner.id === this.props.user.id);
        const isCollaborator = role.roles.includes('collaborator');
        return isCollaborator && idMatch;
      });
      isOwner = this.props.user.id === this.props.owner.id;
    }
```

File: app/collections/show.jsx (hunk 1 above)
Comment (eatyourgreens) [reply app/collections/show.jsx]: Once #4678 is merged, the linter should work on this file.

File: app/collections/show.jsx (hunk 2 above)
Comment (eatyourgreens) [reply app/collections/show.jsx]: Cheers. I rewrote that function to make the logic less complicated to follow. If not… conditions always throw me when I'm reading code.

EsLint is working now, too. 👍

File: app/collections/show.jsx [hunk 3]
```diff
@@ -52,22 +52,21 @@ class CollectionPage extends React.Component {
...
-    if (!this.props.user) {
-      canCollaborate = false;
-    } else {
+  canCollaborate() {
+    const { user } = this.props;
+    let canCollaborate = false;
+    let isOwner = false;
+    if (user && user.id) {
       canCollaborate = this.props.roles.some((role) => {
         const idMatch = (role.links.owner.id === this.props.user.id);
```
Comment (rogerhutchings) [inline app/collections/show.jsx]: You could use `user.id` here as well

Comment (eatyourgreens) [reply app/collections/show.jsx]: Should be fixed now.
