### PR TITLE
Fix volunteer count via constant offset

### LINKED ISSUE #4043: Registered volunteer count on home page is low
According to @mrniaboc we have 1,678,753 registered volunteers; the home page shows a lower number. 

Also, please add more space between the number and "REGISTERED VOLUNTEERS" 

zooniverse

### PR DESCRIPTION
**Pull request by lcjohnso**
Staging branch URL: https://pr-5518.pfe-preview.zooniverse.org

Fixes #4043 following style of #4511 solution.

Offset between true DB user count and the current/old displayed value is because the old count excluded Ouroboros users (where `USERS.OUROBOROS_CREATED` is true).  That population is currently 124921, so that is the offset used in this fix.  I'll note that this number appears to fluctuate with time (?): it was 126571 on 17 May 2019 and ~118600 in Sep 2017.

Edit to initialize counter to 0 in app/pages/home-not-logged-in.jsx follows fix in #4526.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

File: app/pages/home-not-logged-in/research.jsx [hunk 1]
```diff
@@ -41,6 +41,7 @@ counterpart.registerTranslations('en', {
 const GZ123_COUNT = 98989226
 const OUROBOROS_COUNT = 142800311
 const OTHERS_COUNT = 8680290
+const OUROBOROS_USER_COUNT = 124921
```
Comment (camallen) [inline app/pages/home-not-logged-in/research.jsx]: Thanks for naming this well :)

Pity, past us didn't name the other counts with the context of what they are counting :(

File: app/pages/home-not-logged-in.jsx [hunk 2]
```diff
@@ -31,7 +31,7 @@ export default class HomePage extends React.Component {
       featuredProject: null,
       promotedProjects: [],
       screenWidth: 0,
-      volunteerCount: 1500000
+      volunteerCount: 0
```
Comment (camallen) [inline app/pages/home-not-logged-in.jsx]: So this now means the counter starts at 0 on the home page until the API request for users completes?

Comment (lcjohnso) [reply app/pages/home-not-logged-in.jsx]: I think that may be true.  But as we found out during the classification count work (see #4526), this initialization value was being added to the other constant values -and- the returned value, so I mimicked that fix to be sure such an offset didn't occur here.  Not exactly sure how/when the update from initialized value versus API requested value occurs, but know this is the safe route.
