### PR TITLE
Lab: more robust workflow-tutorial links

### LINKED ISSUE #6400: Incorrect Tutorial displaying on workflow
## Current behavior
Original message from project team via the project's private Talk board:
>We're having an issue where the tutorial selected in our workflow isn't the one displaying to users. The Find the Names (Manuscript)** workflow has Tutorial [6402](https://www.zooniverse.org/projects/douglassday/transcribe-shadd-cary/talk/tags/6402) - Find The Names selected. However, Tutorial [6381](https://www.zooniverse.org/projects/douglassday/transcribe-shadd-cary/talk/tags/6381) - Transcription Tutorial 01 is what seems to appear instead. We'd hoped it was a testing issue only, but based on feedback from testers, it shows up in live mode as well. While testing, we tried removing and reselecting the tutorial multiple times, but with no success.

## Replicated once, currently behaving as expected but took several tries
I did encounter some weird behaviors while on the lab page -- It initially showed up as being set to 6402 in the lab workflow page ([workflow 23348](https://www.zooniverse.org/lab/19864/workflows/23348)), but that wasn't reflected on the live project for the workflow in question (red flag no. 1). So I changed that workflow's Tutorial settings to "No tutorial" but it didn't immediately update on the live site (red flag no. 2), and then when I refreshed the Project Builder page, it came up as being set to the incorrect Tutorial [6381](https://www.zooniverse.org/projects/douglassday/transcribe-shadd-cary/talk/tags/6381) (red flag no. 3!). I then changed it to Tutorial 6402 and it seemed to properly reset.

## Additional information
Possibly related to issue zooniverse/panoptes#4104 (seems like changes aren't being saved in the lab? or at least another example of changes in the lab not being reflected on PFE projects)

### PR DESCRIPTION
**Pull request by eatyourgreens**
Update the workflow tutorials widget to allow for a case where Panoptes might erroneously link more than one tutorial of the same type to a single workflow.

Staging branch URL: https://pr-6405.pfe-preview.zooniverse.org/lab

Fixes #6400.

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

### CODE REVIEW

File: app/pages/lab/workflow-components/tutorials.jsx [hunk 1]
```diff
@@ -3,31 +3,37 @@ import apiClient from 'panoptes-client/lib/api-client';
...
+    if (linkedTutorial) {
+      workflow.addLink('tutorials', [linkedTutorial.id]);
+      setLinkedTutorials([linkedTutorial]);
+    } else {
+      setLinkedTutorials([]);
+    }
   }
 
   function onChange(event) {
+    // TODO: radio groups only fire change events for the checked input, so what does this line do?
```
Comment (goplayoutside3) [inline app/pages/lab/workflow-components/tutorials.jsx:36]: Is this comment intentionally left in the PR?

To avoid future devs from "what's this comment for?" I recommend addressing the TODO in this PR or opening a separate Issue for it.

Comment (eatyourgreens) [reply app/pages/lab/workflow-components/tutorials.jsx:36]: This is intentional. What is that line doing? I don’t understand it.

Comment (eatyourgreens) [reply app/pages/lab/workflow-components/tutorials.jsx:36]: Is it safe to remove the following line?

Comment (eatyourgreens) [reply app/pages/lab/workflow-components/tutorials.jsx]: I've removed `shouldAdd` but I wish I knew why it was there in the first place. 🤔

Comment (eatyourgreens) [reply app/pages/lab/workflow-components/tutorials.jsx]: The workflow editor still works without it. 🤷🏻‍♂️

**Review by mcbouslog — APPROVED** [review]
These code changes LGTM 👍 . I confirmed locally on my staging workflow with two linked tutorials (not mini-courses) that when I changed the tutorial or selected no tutorial it not only changed to my selection as expected, but also removed the extra unexpected tutorial link.

The following is optional for this PR or could be a subsequent PR, but I think we can copy-paste these changes to https://github.com/zooniverse/Panoptes-Front-End/blob/workflow-tutorial-links/app/pages/lab/workflow-components/mini-courses.jsx (with an edit for `kind` for mini-course vs tutorial).

The following isn't a request for changes, and I'm not sure about a related solution, but noting that if more than one tutorial (not mini-course) is unexpectedly linked to a workflow, these changes won't show that multiple tutorials are unexpectedly linked. It can't/shouldn't show multiple items selected within a radio input group, so it makes sense why it is as is, but just noting if a workflow gets out of whack with multiple tutorials (not mini-courses) linked it won't show or correct it until a change to the tutorials linked is made.
